# Site settings
title: Ten14 Communications
email: adam.michael.wood@gmail.com
description: >
  How are they to hear?
baseurl: ""
url: "http://faithfilledfinance.com"
twitter_username: jekyllrb
github_username:  adammichaelwood

# Build settings
markdown: kramdown
